# Generated by Django 2.2.10 on 2020-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.SlugField(choices=[('Essential', 'Essential'), ('Professional', 'Professional'), ('Premium', 'Premium')], max_length=20, null=True)),
                ('price_monthly', models.IntegerField(null=True)),
                ('price_yearly', models.IntegerField(null=True)),
                ('discount_rate', models.IntegerField(null=True)),
                ('pack_sec_one', models.CharField(blank=True, max_length=120, null=True)),
                ('pack_sec_two', models.CharField(blank=True, max_length=120, null=True)),
                ('pack_sec_three', models.CharField(blank=True, max_length=120, null=True)),
                ('pack_sec_four', models.CharField(blank=True, max_length=120, null=True)),
                ('pack_sec_five', models.CharField(blank=True, max_length=120, null=True)),
                ('pack_sec_six', models.CharField(blank=True, max_length=120, null=True)),
                ('pack_sec_seven', models.CharField(blank=True, max_length=120, null=True)),
                ('pack_sec_eight', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
    ]
