# Generated by Django 2.2.10 on 2020-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Free', 'Free'), ('Logo', 'Logo'), ('Animation', 'Animation'), ('Video Animation', 'Video Animation'), ('Viper Video', 'Viper Video')], max_length=120, null=True),
        ),
    ]
