# Generated by Django 3.0.5 on 2020-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200627_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_file',
            field=models.FileField(null=True, upload_to='new_file/'),
        ),
    ]
