# Generated by Django 3.0.5 on 2020-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='new_file/'),
        ),
    ]
