# Generated by Django 2.2.14 on 2020-08-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200708_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='store',
            new_name='product',
        ),
    ]
