# Generated by Django 3.1.2 on 2020-11-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200813_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='store',
        ),
    ]
