# Generated by Django 3.1.3 on 2020-11-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('store', '0006_auto_20201109_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(blank=True, default='_', null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
