# Generated by Django 3.1.3 on 2020-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201119_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Free', 'Free'), ('Logo', 'Logo'), ('Animation', 'Animation'), ('Video Animation', 'Video Animation'), ('Viper Video', 'Viper Video')], max_length=120, null=True),
        ),
    ]
