# Generated by Django 2.2.10 on 2020-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20)),
                ('about', models.TextField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('google_plus', models.CharField(max_length=100, null=True)),
                ('pinterest', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('youtube', models.CharField(max_length=100, null=True)),
                ('tumbler', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'social-links',
            },
        ),
        migrations.CreateModel(
            name='overlayLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20)),
                ('link', models.URLField(null=True)),
            ],
            options={
                'db_table': 'overlay-links',
            },
        ),
    ]
