# Generated by Django 3.1.2 on 2020-11-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('idea_category', models.CharField(blank=True, max_length=120, null=True)),
                ('idea_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'custom',
            },
        ),
    ]
