# Generated by Django 3.1.3 on 2020-11-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='categories',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='description',
            field=models.TextField(blank=True, default='_', max_length=1000, null=True),
        ),
    ]
